### ISSUE TITLE
Is it a virus ?

### ISSUE THREAD

**Issue by mutl3y** [rodneymo/rig-monitorv2#59]
Hi, 

Your project looks great and I would love to try it, however the lack of information about yourself and absence of source code makes me dubious, the executable isn't even on Github.

Could you belay my concerns a little please

**Comment by rodneymo** [comment]
It's definetely not a virus! The reason why I have not open source it is documented in my blog. The very first version of the project - shell script based - was obviously open sourced, but for almost a 1 full year there was only 1 person contributing and dozens of forks. So I didn't see the benefit of doing so for the golang version. Nevertheless it's still something I am considering.

In order to appease your mind I'd should direct you to the telegram channel (checkout old messages) as well as the bitcointalk thread

**Comment by mutl3y** [comment]
Many thanks I will head to telegram and read up, I've been working on an xmr-stak monitor utility specifically around cryptonight algorhythms myself , do you have any plans to support custom inputs from other utilities, Am interested in Go too but only a beginner

**Comment by rodneymo** [comment]
Sure. I am open to it as long as it provides additional (operational) value to miners. What's the name of your utility? this one [https://github.com/mutl3y/JJ-s-XMR-STAK-HashRate-Monitor-and-Restart-Tool](url)?
